Add a brand new charming installation (for 0.9 version)
slawkens/myaac pull request #144
Opened 2020-12-19 21:04 UTC by fernandomatos

For better merging, without any friction:

This pull request is based on **develop branch** rather than master branch, used by mistake at #143 

---

Such a great job at MyAAC, it's far better than other alternatives, it deserves a modern setup & configuration.

This pull request adds a new HTML 5, Bootstrap 5, Responsive and Minimalist UI/UX with clean code behind.

## Before
![Captura de tela 2020-12-19 045907](https://user-images.githubusercontent.com/1052507/102684440-4bb66f80-41b7-11eb-8ba6-57ef12180557.png)

## After
https://user-images.githubusercontent.com/1052507/102684579-81a82380-41b8-11eb-82ea-895fdc807bf8.mp4

2020-12-19 22:45 UTC, slawkens commented on install/steps/3-requirements.php
> +echo ($failed) ? '<div class="alert alert-warning"><span>' . $locale['step_requirements_failed'] . '</span></div>' : '';
This needs to be moved to the line 75 (after if($failed))

It's about following message
![image](https://user-images.githubusercontent.com/16687302/102701141-35aabc80-4254-11eb-9ceb-6e12a5145131.png)

2020-12-19 22:58 UTC, slawkens requested changes
I just found one thing that needs to be addresses, the rest is OK.

2020-12-19 23:22 UTC, slawkens approved these changes
Looks good, thanks!

2020-12-21 11:25 UTC, Leesneaks approved these changes

2020-12-22 06:47 UTC, merged